Manually fix manifest to bypass weird lakefile upgrade error
❯ lake test⚠ [3/13] Replayed Batteries.Data.Array.Matchwarning:
././.lake/packages/batteries/././Batteries/Data/Array/Match.lean:55:8:
`Array.get_push` has been deprecated: use `Array.getElem_push` instead✖
[4/13] Building Batteries.Data.String.Basictrace: .>
LEAN_PATH=././.lake/packages/Cli/.lake/build/lib/lean:././.lake/packages/Qq/.lake/build/lib/lean:././.lake/packages/aesop/.lake/build/lib/lean:././.lake/packages/proofwidgets/.lake/build/lib/lean:././.lake/packages/importGraph/.lake/build/lib/lean:././.lake/packages/LeanSearchClient/.lake/build/lib/lean:././.lake/packages/plausible/.lake/build/lib/lean:././.lake/packages/batteries/.lake/build/lib/lean:././.lake/packages/mathlib/.lake/build/lib/lean:./././../lean4-xp-kit/.lake/build/lib/lean:././.lake/build/lib/lean
/Users/utensil/.elan/toolchains/leanprover--lean4---v4.18.0-rc1/bin/lean
-Dlinter.missingDocs=true
././.lake/packages/batteries/././Batteries/Data/String/Basic.lean -R
././.lake/packages/batteries/./. -o
././.lake/packages/batteries/.lake/build/lib/lean/Batteries/Data/String/Basic.olean
-i
././.lake/packages/batteries/.lake/build/lib/lean/Batteries/Data/String/Basic.ilean
-c
././.lake/packages/batteries/.lake/build/ir/Batteries/Data/String/Basic.c
--jsonerror:
././.lake/packages/batteries/././Batteries/Data/String/Basic.lean:11:18:
'String.Pos.ne_zero_of_lt' has already been declarederror:
././.lake/packages/batteries/././Batteries/Data/String/Basic.lean:22:4:
'Substring.commonPrefix' has already been declarederror:
././.lake/packages/batteries/././Batteries/Data/String/Basic.lean:41:4:
'Substring.commonSuffix' has already been declarederror:
././.lake/packages/batteries/././Batteries/Data/String/Basic.lean:61:4:
'Substring.dropPrefix?' has already been declarederror:
././.lake/packages/batteries/././Batteries/Data/String/Basic.lean:71:4:
'Substring.dropSuffix?' has already been declarederror:
././.lake/packages/batteries/././Batteries/Data/String/Basic.lean:85:4:
'String.dropPrefix?' has already been declarederror:
././.lake/packages/batteries/././Batteries/Data/String/Basic.lean:91:4:
'String.dropSuffix?' has already been declarederror:
././.lake/packages/batteries/././Batteries/Data/String/Basic.lean:96:4:
'String.stripPrefix' has already been declarederror:
././.lake/packages/batteries/././Batteries/Data/String/Basic.lean:101:4:
'String.stripSuffix' has already been declarederror: Lean exited with
code 1Some required builds logged failures:-
Batteries.Data.String.Basicerror: build failed